version: 2.1
# Define jobs
jobs:
  e2e-test: # job test
    docker:
      - image: cimg/node:15.8.0-browsers
    resource_class: medium
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{arch}}-{{.Branch}}-{{checksum "package.json"}}
            - v1-dependencies-{{arch}}-{{.Branch}} 
            - v1-dependencies

      - run:
          name: Install dependencies
          command: npm install
          when: on_fail

      - save_cache:
          key: v1-dependencies-{{arch}}-{{.Branch}}-{{checksum "package.json"}}
          paths: 
            - ~/node_modules
      
      - run: npm run ci-test-record
workflows:
    test:
      jobs:
        - e2e-test