version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/install:
          name: Install Dependencies

      - cypress/run:
          name: Testing Project
          requires:
            - Install Dependencies
          debug: 'cypress:cli'
          attach-workspace: true
          command: npm run ci-test

      - cypress/run:
          name: Building Project
          requires:
            - Testing Project
          attach-workspace: true
          command: npm run build

      - cypress/run:
          name: Alpha Netlify Release
          requires:
            - Building Project
          attach-workspace: true
          command: npm run netlify-build
          post-steps:
            - run: npm semantic-release
          filters:
              branches:
                  only: alpha
              