version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/run:
          name: Development Build
          debug: 'cypress:cli'
          build: npm run build
          command: npm run ci-test
          filters:
              branches:
                  ignore:
                    - master