version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/install
          name: Install

      - cypress/run:
          name: Test
          requires:
            - Install
          debug: 'cypress:cli'
          command: npm run ci-test

      - cypress/run:
          name: Build
          requires:
            - Test
          command: npm run build
              