version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/install

      - cypress/run:
          name: Test
          requires:
            - cypress/install
          debug: 'cypress:cli'
          command: npm run ci-test

      - cypress/run:
          name: Build
          requires:
            - cypress/run
          command: npm run build              