version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/install:
          name: Install Dependencies

      - cypress/run:
          name: Testing Project
          requires:
            - Install Dependencies
          debug: 'cypress:cli'
          command: npm run ci-test

      - cypress/run:
          name: Building Project
          requires:
            - Testing Project
          command: npm run build
              